url_hash_shorter/core/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from core import views
from core.apps import CoreConfig


app_name = CoreConfig.name

urlpatterns = [
    path('api/create_url/', views.create_url, name='create_url'),
    path('api/remove_url/<int:url_pk>', views.remove_url, name='remove_url'),
    path('links/', views.links, name='links'),
    path('<slug:slug>/', views.url_redirect, name='url_redirect'),
    path('', views.index, name='index'),
]

url_hash_shorter/url_hash_shorter/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

url_hash_shorter/core/models.py
import hashlib
import secrets
import string

from django.db import models
from django.urls import reverse


class URL(models.Model):

    source_url = models.URLField(unique=True)
    short_slug = models.SlugField(max_length=64, default=None, unique=True)
    salt = models.CharField(default=None, max_length=10)
    views = models.PositiveIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('core:url_redirect', args=(str(self.short_slug),))

    def save(self, *args, **kwargs):
        alphabet = string.ascii_letters + string.digits
        if self.short_slug is None:
            while True:
                salt = ''.join(secrets.choice(alphabet) for i in range(URL._meta.get_field('salt').max_length))
                slug = hashlib.pbkdf2_hmac('sha256', self.source_url.encode('utf-8'), salt.encode('utf-8'), 100000).hex()
                if URL.objects.filter(short_slug=slug).exists():
                    continue
                self.salt = salt
                self.short_slug = slug
                break
        super(URL, self).save(*args, **kwargs)

url_hash_shorter/core/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_http_methods

from core.models import URL


def index(request, template_name='index.html'):
    context = {
        'urls': URL.objects.order_by('-pk'),
        'menu': 'index',
    }
    return render(request, template_name, context=context)


@require_http_methods(['POST', ])
def create_url(request):
    try:
        URL.objects.get(source_url=request.POST['url'])
    except URL.DoesNotExist:
        url = URL.objects.create(source_url=request.POST['url'])
        messages.success(request, 'Спасибо, ваша ссылка успешно создана: <a href="{}">перейти</a>.'.format(url.get_absolute_url()))
    return redirect('core:index')


@require_http_methods(['GET', ])
def remove_url(request, url_pk):
    url = URL.objects.get(pk=url_pk)
    slug = url.short_slug
    source_url = url.source_url
    url.delete()
    messages.error(request, 'Спасибо, ссылка <a href="{href}">{source}</a> успешно удалена'.format(href=slug, source=source_url))
    return redirect('core:links')


def links(request, template_name='links.html'):
    context = {
        'urls': URL.objects.order_by('-pk'),
        'menu': 'links',
    }
    return render(request, template_name, context=context)


def url_redirect(request, slug):
    url = get_object_or_404(URL, short_slug=slug)
    url.views += 1
    url.save()
    return HttpResponseRedirect(url.source_url)

url_hash_shorter/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Сокращение ссылки</title>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- DataTable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <!-- VueJS -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Axios JS -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <style type="text/css">
        * {
            font-family: sans-serif;
            font-weight: 200;
        }
        table th {
            font-weight: bold;
        }
        .btn-primary {
            background-color: #79aec8;
            border: none;
        }
        .btn-primary:hover, .btn-primary:not(:disabled):not(.disabled).active, .btn-primary:not(:disabled):not(.disabled):active, .show>.btn-primary.dropdown-toggle {
            background-color: #417690;
        }
        .header > .row:first-child {
            min-height: 80px;
        }
        .h-left-btn {
            position: relative;
            top: 20px;
            left: 20px;
            float: left;
        }
        .h-right-btn {
            position: relative;
            top: 20px;
            right: 20px;
            float: right;
            display: inline-block;
        }
        .title {
            font-size: 1.3rem;
            color: white;
            background-color: #79aec8;
        }
    </style>
</head>

<body>
    <div id="app">
        <div class="container-fluid header">
            <div class="row">
                <div class="col-12">

                    {% if request.user.is_authenticated %}
                        <div class="dropdown h-left-btn">
                          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if request.user.email %}{{ request.user.email }}{% else %}{{ request.user.username }}{% endif %}
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'admin:login' %}">Админ. панель</a>
                            <a class="dropdown-item" href="{% url 'admin:logout' %}">Выход</a>
                          </div>
                        </div>
                    {% else %}
                        <a class="btn btn-primary h-left-btn" href="{% url 'admin:login' %}">Вход / Админ. панель</a>
                    {% endif %}

                    {% if menu != 'index' %}
                        <a class="btn btn-primary h-right-btn" href="{% url 'core:index' %}">Создать</a>
                    {% endif %}
                    {% if menu != 'links' %}
                        <a class="btn btn-primary h-right-btn" href="{% url 'core:links' %}">Все ссылки</a>
                    {% endif %}
                </div>
            </div>
            {% if messages %}
            <div class="row">
                <div class="col-12 col-lg-8 offset-lg-2">
                  <ul class="list-unstyled messages">
                  {% for message in messages %}
                      <li class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">{{ message|safe }}</li>
                   {% endfor %}
                  </ul>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="container-fluid my-2 p-0">
            <div class="row m-0">
                <div class="col-12 col-lg-8 offset-lg-2">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- DataTable -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

    {% block extra_js %}
    {% endblock %}

</body>
</html>

url_hash_shorter/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <p class="py-2 px-3 m-0 title">Создать ссылку</p>
    <div class="row mx-lg-5 my-lg-3">
        <div class="col-12 my-2 p-0">
            <form class="form-inline" method="post" action="{% url 'core:create_url' %}">
                {% csrf_token %}
                <div class="form-group col-12">
                    <div class="col-sm-10">
                        <input required type="url" name="url" v-model="new_url" placeholder="Введите ссылку для сокращения..." class="form-control w-100 m-1">
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary m-1" :disabled="urls.indexOf(new_url) != -1">Сократить!</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-12 my-2">
            <p v-if="urls.indexOf(new_url) == -1"><span v-if="new_url">Вы хотите сократить ссылку: [[ new_url ]]</span><span v-else>Начните вводить ссылку в поле выше...</span></p>
            <p v-else style="color: red;">Ссылка уже существует в базе: [[ new_url ]]</p>
        </div>
    </div>

{% endblock %}


{% block extra_js %}

    <!-- Optional JavaScript -->
    <script type="text/javascript">
        var app = new Vue({
          delimiters: ['[[', ']]'],
          el: '#app',
          data: {
            new_url: '',
            urls: [{% for u in urls %}'{{ u.source_url }}'{% if forloop.revcounter != 1%}, {% endif %}{% endfor %}]
          }
        })
    </script>

{% endblock %}

url_hash_shorter/templates/links.html
{% extends 'base.html' %}

{% block content %}

    <p class="py-2 px-3 m-0 title">Все ссылки</p>
    <div class="row mt-1 mx-1 p-3">
        <div class="col-12">
            <table id="links">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Код</th>
                    <th>Просмотры</th>
                    <th>Удалить</th>
                </tr>
                </thead>
                <tbody>
                {% for url in urls %}
                <tr>
                    <td>{{ forloop.revcounter }}</td>
                    <td>
                        <a href="{{ url.get_absolute_url }}">{{ url.short_slug|truncatechars:80 }}</a><br/>
                        <small>{{ url.source_url|truncatechars:80 }}</small>
                    </td>
                    <td>{{ url.views }}</td>
                    <td><a href="{% url 'core:remove_url' url.pk %}" class="btn btn-danger">удалить</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}


{% block extra_js %}

    <!-- Optional JavaScript -->
    <script type="text/javascript">
        var app = new Vue({
          delimiters: ['[[', ']]'],
          el: '#app',
          data: {
            new_url: '',
            urls: [{% for u in urls %}'{{ u.source_url }}'{% if forloop.revcounter != 1%}, {% endif %}{% endfor %}]
          }
        })
        $(document).ready(function() {
            $('#links').DataTable( {
                "order": [[ 2, "desc" ]]
            } );
        } );
    </script>

{% endblock %}